### ISSUE TITLE
NavbarText missing style value

### ISSUE THREAD

**Issue by worknperk** [gwtbootstrap/gwt-bootstrap#518]
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#navbar

The NavbarText sites flush with the Navbar. The padding or margin has disappeared.

![capture](https://cloud.githubusercontent.com/assets/10578022/8635613/f53ea33a-27f8-11e5-9cf7-eef791e0da15.PNG)

**Comment by caarlos0** [comment]
gwtbootstrap3 is another project.

**Comment by worknperk** [comment]
Oops. Sorry.
